[build]
  publish = "dist"
  command = "npm run build"

# SPA routing - redirect all non-API requests to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  # Set your Railway backend API URL here (update after deployment)
  VITE_API_URL = "https://your-railway-app.railway.app/api"
